#
# Don't change this file. Copy this file as Makefile.mine and then set the 
# variables. The Makefile.mine will be included by the root Makefile, and 
# will be ignored by .gitignore.
#
# Targets:
#   apps:
#     freertos_blinky
#
APP_NAME = freertos_blinky 

DEBUG = 0

#
# Set to:
# - v9.0.0
#
FREERTOS_KERNEL_VERSION_NUMBER = v9.0.0
