#
# Don't change this file. Copy this file as Makefile.mine and then set the 
# variables. The Makefile.mine will be included by the root Makefile, and 
# will be ignored by .gitignore.
#

#
# Targets:
#   apps:
#     freertos_blinky
#
APP_NAME = freertos_blinky 

#
# Set to 1 to enable debug info.
#
DEBUG = 0

#
# sAPI version to use.
#
SAPI_VERSION_NUMBER = sAPI-r0.5.0

#
# FreeRTOS version to use:
# - v9.0.0
# - v10.1.1
#
FREERTOS_KERNEL_VERSION_NUMBER = v9.0.0
